# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: C12599

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd lenguajes24/C12599/Examen1/Api
        dotnet restore
    - name: Build
      run: |
        cd lenguajes24/C12599/Examen1/Api
        dotnet build --no-restore
    - name: Test
      run: |
        cd lenguajes24/C12599/Examen1/Api
        dotnet test --no-build --verbosity normal
