# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: C22037

on:
  push:
    branches: [ "DevOps_C22037" ]
  pull_request:
    branches: [ "DevOps_C22037" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3407:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: store1
          MYSQL_USER: store1
          MYSQL_PASSWORD: 1234561
    steps:
    - uses: actions/checkout@v4
    - name: Wait for MySQL to be healthy
      run: |
        docker ps -a
        #docker-compose run --rm wait-for-it.sh mysql:3407 -t 30
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd C22037/Docker
        dotnet restore
    - name: Build
      run: |
        cd C22037/Docker
        dotnet build --no-restore
    - name: Test
      run: |
        cd C22037/Docker
        dotnet test --no-build --verbosity normal
  publish-Api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        cd C22037/Docker
        docker image build -t itschaco26/todoapi:latest .
        docker image build -t itschaco26/todoapi:0.0.1 .
        echo "${{ secrets.C22037DOCKERHUBPASS  }}" | docker login -u "aaronchacon2601@gmail.com" --password-stdin
        docker push itschaco26/todoapi:latest
        docker push itschaco26/todoapi:0.0.1
  publish-UI:   
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        cd C22037/Docker/my-app
        docker image build -t itschaco26/react:latest .
        docker image build -t itschaco26/react:0.0.1 .
        echo "${{ secrets.C22037DOCKERHUBPASS  }}" | docker login -u "aaronchacon2601@gmail.com" --password-stdin
        docker push itschaco26/react:latest
        docker push itschaco26/react:0.0.1    
