# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: C22202

on:
  push:
    branches: [ "DevOps_C22202" ]
  pull_request:
    branches: [ "DevOps_C22202" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd C22202/Lab7
        dotnet restore
    - name: Build
      run: |
        cd C22202/Lab7
        dotnet build --no-restore
    - name: Test
      run: |
        cd C22202/Lab7
        dotnet test --no-build --verbosity normal
  publish-Api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        cd C22202/Lab7
        docker image build -t g4b00/lenguajes24shopapi:latest .
        docker image build -t g4b00/lenguajes24shopapi:0.0.1 .
        echo "${{ secrets.DOCKERHUBPASSC22202  }}" | docker login -u "gchavesrojas@gmail.com" --password-stdin
        docker push g4b00/lenguajes24shopapi:latest
        docker push g4b00/lenguajes24shopapi:0.0.1
  publish-UI:   
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        cd C22202/lab6
        docker image build -t g4b00/lenguajes24ui:latest .
        docker image build -t g4b00/lenguajes24ui:0.0.1 .
        echo "${{ secrets.DOCKERHUBPASSC22202  }}" | docker login -u "gchavesrojas@gmail.com" --password-stdin
        docker push g4b00/lenguajes24ui:latest
        docker push g4b00/lenguajes24ui:0.0.1    
