name: C27227

on:
  push:
    branches: [ "C27227_DevOps" ]
  pull_request:
    branches: [ "C27227_DevOps" ]

jobs:
  unitTest:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: store
          MYSQL_USER: root1
          MYSQL_PASSWORD: 123456
    steps:
    - uses: actions/checkout@v4
    - name: Wait for MySQL to be healthy
      run: |
        docker ps -a
        #docker-compose run --rm wait-for-it.sh mysql:3306 -t 30
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd C27227/Examen1_C27227
        dotnet restore
    - name: Build
      run: |
        cd C27227/Examen1_C27227
        dotnet build --no-restore
    - name: Test
      run: |
        cd C27227/Examen1_C27227
        dotnet test --no-build --verbosity normal
  publish-Api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        cd C27227/Examen1_C27227
        docker image build -t kensc/lenguajes2024api:latest .
        docker image build -t kensc/lenguajes2024api:0.0.1 .
        echo "-------------------------------------------------------------------------------------------------------------------"
        echo "${{ secrets.DOCKERHUBPASSC27227  }}"
        echo "${{ secrets.DOCKERHUBPASSC27227  }}" | docker login -u "ks7269281@gmail.com" --password-stdin
        docker push kensc/lenguajes2024api:latest
        docker push kensc/lenguajes2024api:0.0.1
  publish-UI:   
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        cd C27227/Examen1_C27227/nextjs-dashboard
        docker image build -t kensc/lenguajes2024ui:latest .
        docker image build -t kensc/lenguajes2024ui:0.0.1 .
        echo "${{ secrets.DOCKERHUBPASSC27227  }}" | docker login -u "ks7269281@gmail.com" --password-stdin
        docker push kensc/lenguajes2024ui:latest
        docker push kensc/lenguajes2024ui:0.0.1    
