# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: C27507

on:
  push:
    branches: [ "DevOps_C27507" ]
  pull_request:
    branches: [ "DevOps_C27507" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: MyStoreApi
          MYSQL_USER: root
          MYSQL_PASSWORD: 123456                    
    steps:
    - uses: actions/checkout@v4
    - name: Wait for MySQL to be healthy
      run: |
        docker ps -a
        #docker-compose run --rm wait-for-it.sh mysql:3306 -t 30
        
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd C27507/Docker
        dotnet restore
    - name: Build
      run: |
        cd C27507/Docker
        dotnet build --no-restore    
    - name: Test
      run: |
        cd C27507/C27507_Lab7
        dotnet test --no-build --verbosity normal
        
  publish-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        cd C27507/C27507_Lab7
        docker image build -t alvaro944/store_api_leng_2024:latest .
        echo "${{ secret.DOCKERHUBPASS_C27507 }}" | docker login -u "alvaro.siles@ucr.ac.cr" --password-stdin
        docker push alvaro944/store_api_leng_2024:latest
        
  publish-ui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        cd C27507/C27507_Lab1/nodeJS_Lab3/nextjs-dashboard
        docker image build -t alvaro944/store_api_leng_2024:latest .        
        echo "${{ secret.DOCKERHUBPASS_C27507 }}" | docker login -u "alvaro.siles@ucr.ac.cr" --password-stdin
        docker push alvaro944/store_api_leng_2024:latest
      
                
        
